name: 32bit-ci
on:
  push:
    branches:
      - master
  pull_request: {} # Validate all PRs

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        ghc: ['9.12']
    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
    - name: Update cabal package database
      run: cabal update
    - uses: actions/cache@v3
      name: Cache cabal stuff
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}
    - name: Test
      run: |
        cabal sdist -z -o .
        cabal get unordered-containers-*.tar.gz
        cd unordered-containers-*/
        cabal build unordered-containers:tests --enable-tests --enable-benchmarks
        cabal test --enable-tests --enable-benchmarks --test-show-details=direct all
    - name: Bench
      run: |
        cd unordered-containers-*/
        cabal bench --enable-tests --enable-benchmarks --benchmark-option=-l all
    - name: Haddock
      run: |
        cd unordered-containers-*/
        cabal haddock all
    - name: Cabal check
      run: |
        cd unordered-containers-*/
        cabal check

  i386:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: i386/ubuntu:bionic
    steps:
    - name: Install
      run: |
        apt-get update -y
        apt-get install -y autoconf build-essential zlib1g-dev libgmp-dev curl libncurses5 libtinfo5 libncurses5-dev libtinfo-dev
        curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | BOOTSTRAP_HASKELL_NONINTERACTIVE=1 BOOTSTRAP_HASKELL_INSTALL_NO_STACK=1 sh
    - uses: actions/checkout@v1 #This version must stay old enough to remain compatible with the container image
    - name: Test
      run: |
        source ~/.ghcup/env
        cabal update
        cabal test
